### ISSUE TITLE
Helm Release 1.10.3 Missing

### ISSUE THREAD

**Issue by 0nebody** [vmware/load-balancer-and-ingress-services-for-kubernetes#1268]
### Describe the bug

I am trying to follow the install guide for AKO with helm and receiving an error with version 1.10.3 not found.

### Reproduction steps

Following the [install guide](https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/docs/install/helm.md):

```shell
helm show chart oci://projects.registry.vmware.com/ako/helm-charts/ako --version 1.10.3
Error: projects.registry.vmware.com/ako/helm-charts/ako:1.10.3: not found
```

### Expected behavior

Helm release 1.10.3 chart output.

**Comment by akshayhavile** [comment]
@0nebody Are you still facing above issue? It could be CDN specific issue.

**Comment by 0nebody** [comment]
@akshayhavile No, it happened a couple of times but not recently. Thanks.
