### ISSUE TITLE
Github Page with helm installation is outdated

### ISSUE THREAD

**Issue by Bjego** [vmware/load-balancer-and-ingress-services-for-kubernetes#1310]
### Describe the bug

Hey guys,
when I try to follow the steps here: https://avinetworks.github.io/avi-helm-charts/docs/AKO/install/helm.html

then I can't reach the helm repo.
In your markdown files in the code base you are referencing to `oci://projects.registry.vmware.com/ako/helm-charts/ako`, that link seems to work.
Working doc:
https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/docs/install/helm.md

### Reproduction steps

Follow the steps from the github page. The helm install doesn't work

### Expected behavior

A fixed documentation

**Comment by akshayhavile** [comment]
@Bjego Please follow official document website for AKO related info and installation: https://avinetworks.com/docs/ako/1.10/ako-installation/
This page has updated instruction list.
Please do not use link: `https://avinetworks.github.io/avi-helm-charts/docs/AKO/install/helm.html`.
