### ISSUE TITLE
AKO should support assigning static IP for LoadBalancer type Service

### ISSUE THREAD

**Issue by maplain** [vmware/load-balancer-and-ingress-services-for-kubernetes#172]
It's a common request from customers. For now, assigning a static IP in `service.spec.loadBalancerIP` is a noop.

**Comment by maplain** [comment]
@nmandaleeka

**Comment by sudswasavi** [comment]
Looks like we would have to implement the same logic as we do for advancedL4 and static IP specifications on the `Gateway` object there.

**Comment by sudswasavi** [comment]
https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/192 this resolves this bug. Marking it as closed.
