### ISSUE TITLE
AKO should exit allowing the container to restart if IP, credentials, or certificate become invalid

### ISSUE THREAD

**Issue by akutz** [vmware/load-balancer-and-ingress-services-for-kubernetes#182]
Currently AKO will just fail to connect to an endpoint with errors, but not crash, if any of the following information changes:

* The Avi Controller IP
* The username
* The password
* The CA data

Instead, AKO should exit with a non-zero exit code so that Kubernetes will restart AKO and allow it to pick up any new, configuration data via its environment variables.

**Comment by sudswasavi** [comment]
AKO does restart if it detects a 401 error which is thrown with an Invalid credential.
https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/release-1.3.1/internal/rest/dequeue_nodes.go#L170

This will be detected based on an invalid session detection from AKO.
I am not sure if the Avi Controller IP change is straight forward without the controller being in cluster mode. Pls let me know what you find there.

**Comment by akutz** [comment]
Doesn’t this shut down AKO’s API server?

• https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/internal/rest/dequeue_nodes.go#L170
• https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/internal/lib/lib.go#L417
• https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/pkg/api/api.go#L58
• https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/4bece67d4cb62aebb82131a0226ea0d636cfc128/pkg/api/api.go#L64

Does that cause the liveness probe to fail? If so, can you just exit instead? Specific exit codes could be provided to indicate the reason for the pod restarting. A liveness probe failure will not reflect why the restart occurred. Also, this does not take into consideration if the Trusted Root Chain changes. This only accounts for failed credentials, and a string check does not seem too robust to me, but perhaps I’m missing something?

Does it make sense to exit if the ConfigMap or Secret changes? I know you’re not reading that information directly, but if those change then you have a good reason to believe you should restart due to env vars potentially changing. Thoughts?

**Comment by akutz** [comment]
> I am not sure if the Avi Controller IP change is straight forward without the controller being in cluster mode.

If it’s possible at all we should account for it. Even if it isn’t, perhaps someone sets up DNS to talk to Avi and they change the record and want to give you a new FQDN? Supporting it now saves a lot of potential pain later.

**Comment by chauhanshubham** [comment]
AKO reacts to changes in it's secret object and reboots accordingly. I believe this was added in AKO release-1.3.1. Closing this. Thanks.
