### ISSUE TITLE
DNS Profile should be optional in AKO

### ISSUE THREAD

**Issue by maplain** [vmware/load-balancer-and-ingress-services-for-kubernetes#238]
Currently, if DNS Profile is not configured, Service Status can not be patched successfully.

```bash
2020-12-23T00:56:25.425Z	ERROR	status/svc_status.go:37	Service hostname not found for service %v status update[default/test-ip-service]
```

**Comment by sudswasavi** [comment]
This has been fixed in: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/239
