### ISSUE TITLE
Can't Map Selector-less LB Service to the Corresponding Endpoints Object

### ISSUE THREAD

**Issue by iXinqi** [vmware/load-balancer-and-ingress-services-for-kubernetes#428]
**Summary**:
When a LB service without a selector is created and **a few minutes later**, the corresponding Endpoint object is created, AKO 1.4.1 doesn't map the service to the endpoint.

**Detail**:
When a LB service without a selector is created and a few minutes later, the corresponding Endpoint object is created, msg: `error while retrieving endpoints: endpoints "ha-lb" not found` still shows up in the log of pod "ako-0". AKO needs a restart to map the service to the endpoint.

**Comment by sudswasavi** [comment]
Addressed here: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/434
