### ISSUE TITLE
AKO imagePullSecrets‘s format is wrong

### ISSUE THREAD

**Issue by zm1990s** [vmware/load-balancer-and-ingress-services-for-kubernetes#589]
In statefulset.yaml line 19~21, imagePullSecrets's format is wrong, it should be - name: {{ toYaml . }}

Original:
```
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
```
Fix:

```
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{  toYaml . }}
    {{- end }}
```

References:

Official doc:
[https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)

Another helm example:
[https://github.com/Azure-Samples/helm-charts/blob/master/chart-source/image-pull-secret/templates/acs-helloworld.yaml](https://github.com/Azure-Samples/helm-charts/blob/master/chart-source/image-pull-secret/templates/acs-helloworld.yaml)

**Comment by chauhanshubham** [comment]
Thanks for bringing this up. We don't really use the `imagePullSecrets` field and seems to be stale. We'll remove this from the   statefulset spec.
