### ISSUE TITLE
Got security vulnerabilities alert from github when import github.com/vmware/load-balancer-and-ingress-services-for-kubernetes

### ISSUE THREAD

**Issue by XudongLiuHarold** [vmware/load-balancer-and-ingress-services-for-kubernetes#783]
### Describe the bug

I got `We found potential security vulnerabilities in your dependencies` alert when I import `github.com/vmware/load-balancer-and-ingress-services-for-kubernetes` in my go project.

![Imgur](https://i.imgur.com/JQitr7Q.png)

### Reproduction steps

```bash
run `go get github.com/vmware/load-balancer-and-ingress-services-for-kubernetes` in your repo.
```

### Expected behavior

No security vulnerabilities after run `go get github.com/vmware/load-balancer-and-ingress-services-for-kubernetes`

**Comment by akshayhavile** [comment]
@XudongLiuHarold: This has been fixed in recent release. So  I am closing this.
