### ISSUE TITLE
Allow option of setting an icap profile in hostrule

### ISSUE THREAD

**Issue by death5hadow** [vmware/load-balancer-and-ingress-services-for-kubernetes#819]
### Is your feature request related to a problem? Please describe.

Currently there is no possibility of setting the icap profile similarly to f.e. setting an errorpageprofile or applicationProfile.

### Describe the solution you'd like

Allow the addition of an icapProfile in the same way as an erorpageprofile or an applicationprofile

**Comment by alex1989hu** [comment]
fixed https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1103
