### ISSUE TITLE
Alternative to deprecated Service.Spec.LoadBalancerIP

### ISSUE THREAD

**Issue by Zalastax** [vmware/load-balancer-and-ingress-services-for-kubernetes#898]
### Is your feature request related to a problem? Please describe.

`svc.spec.loadBalancerIP` has been deprecated in k8s 1.24: https://github.com/kubernetes/kubernetes/pull/107235. This may lead to problems in the future.

### Describe the solution you'd like

I'd like to see this project add an annotation to assign a Load Balancer IPs. Please see https://github.com/metallb/metallb/pull/1174 for inspiration.

**Comment by swathinsankaran** [comment]
This issue was fixed with PR #994. Hence closing this issue.
